#!/bin/bash
# SETUP WSL2 Linux Filesystem for Docker Performance
# 
# This script creates a complete, minimal project setup in WSL2's home directory
# to fix Docker performance issues on Windows
#
# IMPORTANT: You must do this manually in WSL2 Terminal:
#   1. Open Ubuntu Terminal (press Win+L, type "Ubuntu", press Enter)
#   2. Navigate to your WSL2 home directory: cd ~
#   3. Follow the setup instructions below this script
#
# For the current setup, we've already prepared a clean version
# in the Downloads folder.

echo "\n=== WSL2 Docker Performance Fix Setup ===\n"

echo "To move your project to WSL2 Linux filesystem and fix Docker performance:"
echo ""
echo "Step 1: Close this Windows Command Prompt/PowerShell"
echo ""
echo "Step 2: Open Ubuntu Terminal in WSL2:"
echo "   - Press Windows Key, type 'Ubuntu'"
echo "   - Press Enter to open WSL2 terminal (this has no Windows filesystem)"
echo ""
echo "Step 3: Navigate to WSL2 home directory:"
echo "   cd ~"
echo "   mkdir trace"
echo "   cd trace"
echo ""
echo "Step 4: Copy your current project files to ~/trace:"
echo "   Your project is currently at: /mnt/c/Projects/trace"
echo "   We need to copy these files to ~/trace (WSL2 Linux home)"
echo "   "
echo "   From WSL2 terminal, run:"
echo "   rsync -av /mnt/c/Projects/trace/ ~/trace/"
echo ""
echo "Step 5: If you can't run rsync, use manual copy:"
echo "   # In WSL2 terminal:"
echo "   # Use Windows File Explorer to drag/drop C:\Projects\trace to ~/trace in WSL2"
echo ""
echo "Step 6: After copying complete, replace files with optimized versions:"
echo "   # In WSL2 terminal (cd ~/trace):"
echo "   # Create new Dockerfile:")
echo "   cat > Dockerfile << 'EOF'"
echo "FROM debian:bookworm-slim"
echo ""
echo "RUN apt-get update && apt-get install -y --no-install-recommends \\"
echo "    ca-certificates curl && \\"
echo "    rm -rf /var/lib/apt/lists/*"
echo ""
echo "RUN useradd -m -s /bin/bash supermemory"
echo ""
echo "USER supermemory"
echo "WORKDIR /home/supermemory"
echo ""
echo "ENV SUPERMEMORY_NO_PROMPT=1"
echo "ENV SUPERMEMORY_DATA_DIR=/home/supermemory/data"
echo "RUN curl -fsSL https://supermemory.ai/install | bash && \\"
echo "    chown -R supermemory:supermemory /home/supermemory/data && \\"
echo "    chmod -R 755 /home/supermemory/data"
echo ""
echo "EXPOSE 6767"
echo "ENTRYPOINT [\"/home/supermemory/.local/bin/supermemory-server\"]"
echo "EOF"
echo ""
echo "   # Create new docker-compose.yml:")
echo "   cat > docker-compose.yml << 'EOF'"
echo "services:"
echo "  supermemory:"
echo "    build:"
echo "      context: ."
echo "      dockerfile: Dockerfile"
echo "    container_name: trace-supermemory"
echo "    ports:"
echo "      - \"6767:6767\""
echo "    volumes:"
echo "      - supermemory-data:/home/supermemory/data"
echo "    env_file:"
echo "      - .env.docker"
echo "    restart: unless-stopped"
echo ""
echo "volumes:"
echo "  supermemory-data:"
echo "EOF"
echo ""
echo "   # Create .env.docker:")
echo "   cat > .env.docker << 'EOF'"
echo "SUPERMEMORY_DATA_DIR=/home/supermemory/data"
echo "SUPERMEMORY_NO_PROMPT=1"
echo "EOF"
echo ""
echo "Step 7: Create minimal supermemory-data files (clean version):"
echo "   mkdir -p supermemory-data"
echo "   touch supermemory-data/{api-key,auth-secret,embedding-plan.json,instance-id,machine-key}"
echo ""
echo "Step 8: Create test directory structure (optional):"
echo "   mkdir -p public"
echo "   echo '<?php echo \"Hello WSL2 and Docker!\"; ?>' > public/index.php"
echo ""
echo "Step 9: Build and start Docker (fast!):"
echo "   docker-compose up -d"
echo ""
echo "Step 10: Verify success:"
echo "   docker-compose logs"
echo ""
echo "===================================================="
echo ""
echo "Result: Your project now lives in WSL2 Linux filesystem (~/)"
echo "Docker will access files from same filesystem as WSL2 = 10x faster!"
echo "Your laptop will be much snappier."
echo ""
echo "To clean up later:"
echo "   docker-compose down --rmi all"
echo ""
